@echo off

set FRONTEND_PROCESS_TITLE=dp-frontend
set BACKEND_PROCESS_TITLE=dp-backend
set TEXTLISTENER_PROCESS_TITLE=dp-textlistener
set TEXTRANKCALC_PROCESS_TITLE=dp-textrankcalc
for /f "tokens=1,2 delims==" %%a in (config\config.ini) do (
	if %%a==FRONTEND_PROCESS_TITLE set FRONTEND_PROCESS_TITLE=%%b
	if %%a==BACKEND_PROCESS_TITLE set BACKEND_PROCESS_TITLE=%%b
	if %%a==TEXTLISTENER_PROCESS_TITLE set TEXTLISTENER_PROCESS_TITLE=%%b
	if %%a==TEXTRANKCALC_PROCESS_TITLE set TEXTRANKCALC_PROCESS_TITLE=%%b
)

echo STOPPING FRONTEND
taskkill /FI "WINDOWTITLE eq %FRONTEND_PROCESS_TITLE%"

echo STOPPING BACKEND
taskkill /FI "WINDOWTITLE eq %BACKEND_PROCESS_TITLE%"

echo STOPPING TEXTLISTENER
taskkill /FI "WINDOWTITLE eq %TEXTLISTENER_PROCESS_TITLE%"

echo STOPPING TEXTRANKCALC
taskkill /FI "WINDOWTITLE eq %TEXTRANKCALC_PROCESS_TITLE%"
